apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peertube.postfix.fullname" . }}
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.postfix.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.postfix.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "peertube.postfix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "peertube.postfix.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.secrets.postfix.my_hostname }}"
      {{- with .Values.postfix.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "peertube.serviceAccountName" . }}
      {{- with .Values.postfix.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: postfix
        {{- with .Values.postfix.PodSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.postfix.image.name }}:{{ .Values.postfix.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.postfix.image.pullPolicy }}
        ports:
        {{- range .Values.postfix.service.ports }}
        {{- if or (typeIsLike "int" .targetPort) (typeIsLike "int64" .targetPort) (typeIsLike "float64" .targetPort) }}
        - name: {{ default "unknown" .name }}
          containerPort: {{ .targetPort }}
        {{- else }}
        - name: {{ default .name .targetPort }}
          containerPort: {{ .port }}
        {{- end }}
          protocol: {{ .protocol | default "TCP" }}
        {{- end }}
        {{- with .Values.postfix.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.postfix.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.postfix.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: TZ
          value: {{ .Values.tz }}
        - name: POSTFIX_myhostname
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.postfix.fullname" . }}-env
              key: postfix_myhostname
        - name: OPENDKIM_DOMAINS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.postfix.fullname" . }}-env
              key: opendkim_domains
        - name: OPENDKIM_RequireSafeKeys
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.postfix.fullname" . }}-env
              key: opendkim_require_safe_keys
        volumeMounts:
        - name: postfix-data
          mountPath: "/etc/opendkim/keys"
        {{- with .Values.postfix.volumeMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: postfix-data
        {{- if (hasKey .Values.postfix.hostPath "postfixData") }}
        hostPath:
          path: "{{ .Values.postfix.hostPath.postfixData.path }}"
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "peertube.postfix.fullname" . }}-data
        {{- end }}
      {{- with .Values.postfix.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.postfix.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.postfix.affinity }}
      affinity:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.postfix.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
