apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peertube.node.fullname" . }}
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.node.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "peertube.node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "peertube.node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.secrets.common.domain }}"
      {{- with .Values.node.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "peertube.serviceAccountName" . }}
      {{- with .Values.node.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: peertube-init
        {{- with .Values.node.PodSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.node.image.name }}:{{ .Values.node.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.node.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - |
          rm -rf /srv/app/client/dist/{*,.*}
          cp -vrfp /app/client/dist/* /srv/app/client/dist/
          cp -vrfpH /config/* /srv/config/
        env:
        - name: TZ
          value: {{ .Values.tz }}
        volumeMounts:
        - name: assets
          mountPath: "/srv/app/client/dist"
        - name: config-prod
          mountPath: "/config/production.yaml"
          subPath: "production.yaml"
        - name: config-custom-env
          mountPath: "/config/custom-environment-variables.yaml"
          subPath: "custom-environment-variables.yaml"
        - name: config
          mountPath: "/srv/config"
      containers:
      - name: peertube
        securityContext:
          privileged: true
        {{- with .Values.node.PodSecurityContext }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.node.image.name }}:{{ .Values.node.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.node.image.pullPolicy }}
        command:
        - /usr/local/bin/entrypoint.sh
        args:
        - /usr/local/bin/node
        - dist/server
        ports:
        {{- range .Values.node.service.ports }}
        {{- if or (typeIsLike "int" .targetPort) (typeIsLike "int64" .targetPort) (typeIsLike "float64" .targetPort) }}
        - name: {{ default "unknown" .name }}
          containerPort: {{ .targetPort }}
        {{- else }}
        - name: {{ default .name .targetPort }}
          containerPort: {{ .port }}
        {{- end }}
          protocol: {{ .protocol | default "TCP" }}
        {{- end }}
        {{- range .Values.node.serviceRtmp.ports }}
        {{- if or (typeIsLike "int" .targetPort) (typeIsLike "int64" .targetPort) (typeIsLike "float64" .targetPort) }}
        - name: {{ default "unknown" .name }}
          containerPort: {{ .targetPort }}
        {{- else }}
        - name: {{ default .name .targetPort }}
          containerPort: {{ .port }}
        {{- end }}
          protocol: {{ .protocol | default "TCP" }}
        {{- end }}
        {{- with .Values.node.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.node.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.node.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: TZ
          value: {{ .Values.tz }}
        - name: PEERTUBE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_secret
        - name: PEERTUBE_TRUST_PROXY
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_trust_proxy
        - name: PEERTUBE_WEBSERVER_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_webserver_hostname
        - name: PEERTUBE_WEBSERVER_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_webserver_port
        - name: PEERTUBE_WEBSERVER_HTTPS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_webserver_https
        - name: PEERTUBE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_db_name
        - name: PEERTUBE_DB_SUFFIX
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_db_suffix
        - name: PEERTUBE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_db_username
        - name: PEERTUBE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_db_password
        - name: PEERTUBE_DB_SSL
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_db_ssl
        - name: PEERTUBE_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_log_level
        - name: PEERTUBE_SIGNUP_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_signup_enabled
        - name: PEERTUBE_TRANSCODING_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_transcoding_enabled
        - name: PEERTUBE_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_smtp_username
        - name: PEERTUBE_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_smtp_password
        - name: PEERTUBE_SMTP_HOSTNAME
          value: {{ include "peertube.postfix.fullname" . }}.{{ include "peertube.namespace" . }}.svc
        - name: PEERTUBE_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_smtp_port
        - name: PEERTUBE_SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_smtp_from
        - name: PEERTUBE_SMTP_TLS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_smtp_tls
        - name: PEERTUBE_SMTP_DISABLE_STARTTLS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_smtp_disable_starttls
        - name: PEERTUBE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube_admin_email
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: assets
          mountPath: "/app/client/dist"
        - name: data
          mountPath: "/data"
        - name: dri
          mountPath: "/dev/dri"
        {{- if eq .Values.arch "rockchip" }}
        - name: dma-heap
          mountPath: "/dev/dma_heap"
        - name: rga
          mountPath: "/dev/rga"
        - name: mpp-service
          mountPath: "/dev/mpp_service"
        {{- end }}
        {{- with .Values.node.volumeMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: config-prod
        secret:
          secretName: {{ include "peertube.node.fullname" . }}-config-prod
      - name: config-custom-env
        configMap:
          name: {{ include "peertube.node.fullname" . }}-config-custom-env
      - name: config
        {{- if (hasKey .Values.config "hostPath") }}
        hostPath:
          path: "{{ .Values.config.hostPath.path }}"
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "peertube.fullname" . }}-config
        {{- end }}
      - name: assets
        {{- if (hasKey .Values.assets "hostPath") }}
        hostPath:
          path: "{{ .Values.assets.hostPath.path }}"
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "peertube.fullname" . }}-assets
        {{- end }}
      - name: data
        {{- if (hasKey .Values.data "hostPath") }}
        hostPath:
          path: "{{ .Values.data.hostPath.path }}"
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "peertube.fullname" . }}-data
        {{- end }}
      - name: dri
        hostPath:
          path: /dev/dri
      {{- if eq .Values.arch "rockchip" }}
      - name: dma-heap
        hostPath:
          path: /dev/dma_heap
      - name: rga
        hostPath:
          path: /dev/rga
      - name: mpp-service
        hostPath:
          path: /dev/mpp_service
      {{- end }}
      {{- with .Values.node.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.node.affinity }}
      affinity:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
