apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peertube.node.fullname" . }}
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.node.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "peertube.node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "peertube.node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.secrets.common.domain }}"
      {{- with .Values.node.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "peertube.serviceAccountName" . }}
      {{- with .Values.node.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: proxy
        {{- with .Values.node.PodSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.node.image.name }}:{{ .Values.node.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.node.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - |
          cp -Hvrfp /srv/config/* /config/
          exec /usr/local/bin/node dist/server
        ports:
        {{- range .Values.node.service.ports }}
        {{- if or (typeIsLike "int" .targetPort) (typeIsLike "int64" .targetPort) (typeIsLike "float64" .targetPort) }}
        - name: {{ default "unknown" .name }}
          containerPort: {{ .targetPort }}
        {{- else }}
        - name: {{ default .name .targetPort }}
          containerPort: {{ .port }}
        {{- end }}
          protocol: {{ .protocol | default "TCP" }}
        {{- end }}
        {{- with .Values.node.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.node.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.node.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: TZ
          value: {{ .Values.tz }}
        - name: PEERTUBE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-secret
        - name: PEERTUBE_TRUST_PROXY
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-trust-proxy
        - name: PEERTUBE_WEBSERVER_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-webserver-hostname
        - name: PEERTUBE_WEBSERVER_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-webserver-port
        - name: PEERTUBE_WEBSERVER_HTTPS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-webserver-https
        - name: PEERTUBE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-db-name
        - name: PEERTUBE_DB_SUFFIX
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-db-suffix
        - name: PEERTUBE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-db-username
        - name: PEERTUBE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-db-password
        - name: PEERTUBE_DB_SSL
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-db-ssl
        - name: PEERTUBE_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-log-level
        - name: PEERTUBE_SIGNUP_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-signup-enabled
        - name: PEERTUBE_TRANSCODING_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-transcoding-enabled
        - name: PEERTUBE_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-smtp-username
        - name: PEERTUBE_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-smtp-password
        - name: PEERTUBE_SMTP_HOSTNAME
          value: {{ include "peertube.postfix.fullname" . }}.{{ include "peertube.namespace" . }}.svc
        - name: PEERTUBE_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-smtp-port
        - name: PEERTUBE_SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-smtp-from
        - name: PEERTUBE_SMTP_TLS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-smtp-tls
        - name: PEERTUBE_SMTP_DISABLE_STARTTLS
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-smtp-disable-starttls
        - name: PEERTUBE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ include "peertube.node.fullname" . }}-env
              key: peertube-admin-email
        volumeMounts:
        - name: config
          mountPath: "/srv/config/production.yaml"
          subPath: "production.yaml"
        - name: custom-env-config
          mountPath: "/srv/config/custom-environment-variables.yaml"
          subPath: "custom-environment-variables.yaml"
        - name: assets
          mountPath: "/app/client/dist"
        - name: data
          mountPath: "/data"
        {{- with .Values.node.volumeMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "peertube.node.fullname" . }}-config
      - name: custom-env-config
        configMap:
          name: {{ include "peertube.node.fullname" . }}-custom-env-config
      - name: assets
        {{- if (hasKey .Values.assets "hostPath") }}
        hostPath:
          path: "{{ .Values.assets.hostPath.path }}"
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "peertube.fullname" . }}-assets
        {{- end }}
      - name: data
        {{- if (hasKey .Values.data "hostPath") }}
        hostPath:
          path: "{{ .Values.data.hostPath.path }}"
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "peertube.fullname" . }}-data
        {{- end }}
      {{- with .Values.node.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.node.affinity }}
      affinity:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
