{{- $ns := (include "peertube.namespace" .) }}
# Generate secret peertube config
{{- $pgSvc := printf "%s.%s.svc" (include "peertube.pg.fullname" .) $ns }}
{{- $redisSvc := printf "%s.%s.svc" (include "peertube.redis.fullname" .) $ns }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-config
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
{{- $path := printf "configs/%s/peertube/config.yaml" .Values.env }}
{{ .Files.Get $path | replace "web_host" .Values.secrets.common.domain | replace "pg_host" $pgSvc | replace "pg_db_name" .Values.secrets.pg.dbName | replace "pg_user" .Values.secrets.pg.dbUser | replace "pg_pass" .Values.secrets.pg.dbPass | replace "redis_host" $redisSvc | b64enc | indent 4 }}
---
# Generate secret peertube env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  peertube-secret: {{ .Values.secrets.peertube.secret | b64enc }}
  peertube-trust_proxy: {{ .Values.secrets.peertube.trustProxy | b64enc }}
  peertube-webserver-hostname: {{ .Values.secrets.common.domain | b64enc }}
  peertube-db-ssl: {{ .Values.secrets.peertube.dbSsl | b64enc }}
  peertube-db-name: {{ .Values.secrets.pg.dbName | b64enc }}
  peertube-db-suffix: {{ .Values.secrets.peertube.dbSuffix | b64enc }}
  peertube-db-username: {{ .Values.secrets.pg.dbUser | b64enc }}
  peertube-db-password: {{ .Values.secrets.pg.dbPass | b64enc }}
  peertube-webserver-port: {{ .Values.secrets.peertube.webserverPort | b64enc }}
  peertube-webserver-https: {{ .Values.secrets.peertube.webserverHttps | b64enc }}
  peertube-log-level: {{ .Values.secrets.peertube.logLevel | b64enc }}
  peertube-signup-enabled: {{ .Values.secrets.peertube.signupEnabled | b64enc }}
  peertube-transcoding-enabled: {{ .Values.secrets.peertube.transcodingEnabled | b64enc }}
  peertube-contact-form-enabled: {{ .Values.secrets.peertube.contactFormEnabled | b64enc }}
  peertube-smtp-username: {{ .Values.secrets.peertube.smtpUsername | b64enc }}
  peertube-smtp-password: {{ .Values.secrets.peertube.smtpPassword | b64enc }}
  peertube-smtp-port: {{ .Values.secrets.peertube.smtpPort | b64enc }}
  peertube-smtp-from: {{ .Values.secrets.peertube.smtpFrom | b64enc }}
  peertube-smtp-tls: {{ .Values.secrets.peertube.smtpTls | b64enc }}
  peertube-smtp-disable-starttls: {{ .Values.secrets.peertube.smtpDisableStarttls| b64enc }}
  peertube-admin-email: {{ .Values.secrets.peertube.smtpAdminEmail | b64enc }}
---
# Generate secret pg env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.pg.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.pg.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-db: {{ .Values.secrets.pg.dbName | b64enc }}
  postgres-user: {{ .Values.secrets.pg.dbUser | b64enc }}
  postgres-password: {{ .Values.secrets.dbPass | b64enc }}
---
