{{- $ns := (include "peertube.namespace" .) }}
# Generate configmap nginx config
{{- $nodeSvc := printf "%s.%s.svc" (include "peertube.node.fullname" .) $ns }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peertube.proxy.fullname" . }}-config
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.proxy.labels" . | nindent 4 }}
data:
{{- if .Values.secrets.proxy.ssl_enable }}
{{- $path := printf "configs/%s/nginx/peertube-ssl.conf" .Values.arch }}
{{ ($.Files.Glob $path).AsConfig | replace "${WEBSERVER_HOST}" .Values.secrets.common.domain | replace "${PEERTUBE_HOST}" (printf "%s:9000" $nodeSvc) | replace "${LIMIT_RATE}" .Values.secrets.proxy.limit_rate | indent 2 }}
{{- else }}
{{- $path := printf "configs/%s/nginx/peertube.conf" .Values.arch }}
{{ ($.Files.Glob $path).AsConfig | replace "${WEBSERVER_HOST}" .Values.secrets.common.domain | replace "${PEERTUBE_HOST}" (printf "%s:9000" $nodeSvc) | replace "${LIMIT_RATE}" .Values.secrets.proxy.limit_rate | indent 2 }}
{{- end }}
---
# Generate configmap peertube custom env config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peertube.node.fullname" . }}-config-custom-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
data:
{{- $path := printf "configs/%s/peertube/custom-environment-variables.yaml" .Values.arch }}
{{ ($.Files.Glob $path).AsConfig | indent 2 }}
---
