{{- $ns := (include "peertube.namespace" .) }}
# Generate secret peertube config
{{- $pgSvc := printf "%s.%s.svc" (include "peertube.pg.fullname" .) $ns }}
{{- $redisSvc := printf "%s.%s.svc" (include "peertube.redis.fullname" .) $ns }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-config
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
{{- $path := printf "configs/%s/peertube/config.yaml" .Values.env }}
{{ .Files.Get $path | replace "web_host" .Values.secrets.common.domain | replace "pg_host" $pgSvc | replace "pg_db_name" .Values.secrets.pg.dbName | replace "pg_user" .Values.secrets.pg.dbUser | replace "pg_pass" .Values.secrets.pg.dbPass | replace "redis_host" $redisSvc | b64enc | indent 4 }}
---
