{{- $ns := (include "peertube.namespace" .) }}
# Generate secret peertube config
{{- $pgSvc := printf "%s.%s.svc" (include "peertube.pg.fullname" .) $ns }}
{{- $redisSvc := printf "%s.%s.svc" (include "peertube.redis.fullname" .) $ns }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-config-prod
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  production.yaml: |-
{{- $path := printf "configs/%s/peertube/production.yaml" .Values.env }}
{{ .Files.Get $path | replace "web_host" .Values.secrets.common.domain | replace "pg_host" $pgSvc | replace "pg_db_name" .Values.secrets.pg.db_name | replace "pg_user" .Values.secrets.pg.db_user | replace "pg_pass" .Values.secrets.pg.db_pass | replace "redis_host" $redisSvc | b64enc | indent 4 }}
---
# Generate secret peertube env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  peertube_secret: {{ .Values.secrets.peertube.secret | toString | b64enc }}
  peertube_trust_proxy: {{ .Values.secrets.peertube.trust_proxy | toJson | b64enc }}
  peertube_webserver_hostname: {{ .Values.secrets.common.domain | toString | b64enc }}
  peertube_db_ssl: {{ .Values.secrets.peertube.db_ssl | toString | b64enc }}
  peertube_db_name: {{ .Values.secrets.pg.db_name | toString | b64enc }}
  peertube_db_suffix: {{ .Values.secrets.peertube.db_suffix | toString | b64enc }}
  peertube_db_username: {{ .Values.secrets.pg.db_user | toString | b64enc }}
  peertube_db_password: {{ .Values.secrets.pg.db_pass | toString | b64enc }}
  peertube_webserver_port: {{ .Values.secrets.peertube.webserver_port | toString | b64enc }}
  peertube_webserver_https: {{ .Values.secrets.peertube.webserver_https | toString | b64enc }}
  peertube_log_level: {{ .Values.secrets.peertube.log_level | toString | b64enc }}
  peertube_signup_enabled: {{ .Values.secrets.peertube.signup_enabled | toString | b64enc }}
  peertube_transcoding_enabled: {{ .Values.secrets.peertube.transcoding_enabled | toString | b64enc }}
  peertube_contact_form_enabled: {{ .Values.secrets.peertube.contact_form_enabled | toString | b64enc }}
  peertube_smtp_username: {{ .Values.secrets.peertube.smtp_username | toString | b64enc }}
  peertube_smtp_password: {{ .Values.secrets.peertube.smtp_password | toString | b64enc }}
  peertube_smtp_port: {{ .Values.secrets.peertube.smtp_port | toString | b64enc }}
  peertube_smtp_from: {{ .Values.secrets.peertube.smtp_from | toString | b64enc }}
  peertube_smtp_tls: {{ .Values.secrets.peertube.smtp_tls | toString | b64enc }}
  peertube_smtp_disable_starttls: {{ .Values.secrets.peertube.smtp_disable_starttls | toString | b64enc }}
  peertube_admin_email: {{ .Values.secrets.peertube.smtp_admin_email | toString | b64enc }}
---
# Generate secret pg env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.pg.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.pg.labels" . | nindent 4 }}
type: Opaque
data:
  postgres_db: {{ .Values.secrets.pg.db_name | toString | b64enc }}
  postgres_user: {{ .Values.secrets.pg.db_user | toString | b64enc }}
  postgres_password: {{ .Values.secrets.pg.db_pass | toString | b64enc }}
---
# Generate secret postfix env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.postfix.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.postfix.labels" . | nindent 4 }}
type: Opaque
data:
  postfix_myhostname: {{ .Values.secrets.postfix.my_hostname | toString | b64enc }}
  opendkim_domains: {{ .Values.secrets.postfix.opendkim_domains | toString | b64enc }}
  opendkim_require_safe_keys: {{ .Values.secrets.postfix.opendkim_require_safe_keys | toString | b64enc }}
---
# Generate secret runner env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.runner.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.runner.labels" . | nindent 4 }}
type: Opaque
data:
  user_name: {{ .Values.secrets.runner.user_name | toString | b64enc }}
  home: {{ .Values.secrets.runner.home | toString | b64enc }}
  registered_instance_url: {{ .Values.secrets.runner.registered_instance_url | toString | b64enc }}
  registered_instance-runner_token: {{ .Values.secrets.runner.registered_instance_runner_token | toString | b64enc }}
  registered_instance_runner_name: {{ default "default" .Values.secrets.runner.registered_instance_runner_name | toString | b64enc }}
  jobs_concurrency: {{ .Values.secrets.runner.jobs_concurrency | toString | b64enc }}
  ffmpeg_threads: {{ .Values.secrets.runner.ffmpeg_threads | toString | b64enc }}
  ffmpeg_nice: {{ .Values.secrets.runner.ffmpeg_nice | toString | b64enc }}
---
