{{- $ns := (include "peertube.namespace" .) }}
# Generate secret peertube config
{{- $pgSvc := printf "%s.%s.svc" (include "peertube.pg.fullname" .) $ns }}
{{- $redisSvc := printf "%s.%s.svc" (include "peertube.redis.fullname" .) $ns }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-config
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
{{- $path := printf "configs/%s/peertube/config.yaml" .Values.env }}
{{ .Files.Get $path | replace "web_host" .Values.secrets.common.domain | replace "pg_host" $pgSvc | replace "pg_db_name" .Values.secrets.pg.dbName | replace "pg_user" .Values.secrets.pg.dbUser | replace "pg_pass" .Values.secrets.pg.dbPass | replace "redis_host" $redisSvc | b64enc | indent 4 }}
---
# Generate secret peertube env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.node.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.node.labels" . | nindent 4 }}
type: Opaque
data:
  peertube-secret: {{ .Values.secrets.peertube.secret | toString | b64enc }}
  peertube-trust-proxy: {{ .Values.secrets.peertube.trustProxy | toJson | b64enc }}
  peertube-webserver-hostname: {{ .Values.secrets.common.domain | toString | b64enc }}
  peertube-db-ssl: {{ .Values.secrets.peertube.dbSsl | toString | b64enc }}
  peertube-db-name: {{ .Values.secrets.pg.dbName | toString | b64enc }}
  peertube-db-suffix: {{ .Values.secrets.peertube.dbSuffix | toString | b64enc }}
  peertube-db-username: {{ .Values.secrets.pg.dbUser | toString | b64enc }}
  peertube-db-password: {{ .Values.secrets.pg.dbPass | toString | b64enc }}
  peertube-webserver-port: {{ .Values.secrets.peertube.webserverPort | toString | b64enc }}
  peertube-webserver-https: {{ .Values.secrets.peertube.webserverHttps | toString | b64enc }}
  peertube-log-level: {{ .Values.secrets.peertube.logLevel | toString | b64enc }}
  peertube-signup-enabled: {{ .Values.secrets.peertube.signupEnabled | toString | b64enc }}
  peertube-transcoding-enabled: {{ .Values.secrets.peertube.transcodingEnabled | toString | b64enc }}
  peertube-contact-form-enabled: {{ .Values.secrets.peertube.contactFormEnabled | toString | b64enc }}
  peertube-smtp-username: {{ .Values.secrets.peertube.smtpUsername | toString | b64enc }}
  peertube-smtp-password: {{ .Values.secrets.peertube.smtpPassword | toString | b64enc }}
  peertube-smtp-port: {{ .Values.secrets.peertube.smtpPort | toString | b64enc }}
  peertube-smtp-from: {{ .Values.secrets.peertube.smtpFrom | toString | b64enc }}
  peertube-smtp-tls: {{ .Values.secrets.peertube.smtpTls | toString | b64enc }}
  peertube-smtp-disable-starttls: {{ .Values.secrets.peertube.smtpDisableStarttls | toString | b64enc }}
  peertube-admin-email: {{ .Values.secrets.peertube.smtpAdminEmail | toString | b64enc }}
---
# Generate secret pg env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.pg.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.pg.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-db: {{ .Values.secrets.pg.dbName | toString | b64enc }}
  postgres-user: {{ .Values.secrets.pg.dbUser | toString | b64enc }}
  postgres-password: {{ .Values.secrets.pg.dbPass | toString | b64enc }}
---
# Generate secret postfix env
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.postfix.fullname" . }}-env
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.postfix.labels" . | nindent 4 }}
type: Opaque
data:
  postfix-myhostname: {{ .Values.secrets.postfix.myHostname | toString | b64enc }}
  opendkim-domains: {{ .Values.secrets.postfix.opendkimDomains | toString | b64enc }}
  opendkim-requiresafekeys: {{ .Values.secrets.postfix.opendkimRequireSafeKeys | toString | b64enc }}
---
