{{- if .Values.assets.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peertube.fullname" . }}-assets
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.assets.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.assets.storage.storageSize }}
  storageClassName: {{ .Values.assets.storage.storageClassName }}
---
{{- end }}
{{- if .Values.data.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peertube.fullname" . }}-data
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.data.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.data.storage.storageSize }}
  storageClassName: {{ .Values.data.storage.storageClassName }}
---
{{- end }}
{{- if (hasKey .Values.pg.storage "pgData") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peertube.pg.fullname" . }}-data
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.pg.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.pg.storage.pgData.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pg.storage.pgData.storageSize }}
  storageClassName: {{ .Values.pg.storage.pgData.storageClassName }}
---
{{- end }}
{{- if (hasKey .Values.redis.storage "redisData") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peertube.redis.fullname" . }}-data
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.redis.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.redis.storage.redisData.accessModes }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.redisData.storageSize }}
  storageClassName: {{ .Values.redis.storage.redisData.storageClassName }}
---
{{- end }}
{{- if (hasKey .Values.postfix.storage "postfixData") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peertube.postfix.fullname" . }}-data
  namespace: {{ include "peertube.namespace" . }}
  labels:
    {{- include "peertube.postfix.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.redis.storage.postfixData.accessModes }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.postfixData.storageSize }}
  storageClassName: {{ .Values.redis.storage.postfixData.storageClassName }}
---
{{- end }}
