{{- if .Values.proxy.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peertube.proxy.fullname" . }}
  labels:
    {{- include "peertube.proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
  {{- range .Values.proxy.service.ports }}
  - name: {{ default "unknown" .name }}
    port: {{ .port }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
    targetPort: {{ default .port .targetPort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "peertube.proxy.selectorLabels" . | nindent 4 }}
{{- end }}
